(deftheme eighters
  "Eighters gonna eight.")

(custom-theme-set-faces
 'eighters
 '(escape-glyph ((t (:foreground "red1"))))
 '(minibuffer-prompt ((t (:foreground "steelblue1" :weight bold))))
 '(highlight ((t (:background "gray25"))))
 '(region ((t (:background "blue" :foreground "white"))))
 '(font-lock-builtin-face ((t (:foreground "steelblue1" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "red1" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "magenta"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "steelblue1" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "cyan" :weight bold))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-string-face ((t (:foreground "lime green" :slant italic))))
 '(font-lock-type-face ((t (:foreground "green3" :slant italic))))
 '(font-lock-variable-name-face ((t (:foreground "gold"))))
 '(link ((t (:underline t :foreground "steelblue1"))))
 '(isearch-fail ((t (:background "red2"))))
 '(lazy-highlight ((t (:foreground "darkturquoise" :background "darkcyan"))))
 '(match ((t (:background "royalblue3"))))
 '(compilation-mode-line-exit((t (:foreground "green3" :inherit (compilation-info)))))
 '(error ((t (:foreground "red1" :weight bold))))
 '(ediff-even-diff-A ((t (:background "gray25"))))
 '(ediff-odd-diff-A ((t (:background "gray25"))))
 '(ediff-even-diff-B ((t (:background "gray25"))))
 '(ediff-odd-diff-B ((t (:background "gray25"))))
 '(ediff-even-diff-C ((t (:background "gray25"))))
 '(ediff-odd-diff-C ((t (:background "gray25"))))
 '(ediff-even-diff-Ancestor ((t (:background "gray25"))))
 '(ediff-odd-diff-Ancestor ((t (:background "gray25"))))
 '(ediff-current-diff-A ((t (:background "#3f2900"))))
 '(ediff-current-diff-B ((t (:background "#07243F"))))
 '(ediff-current-diff-C ((t (:background "#2a2a08"))))
 '(ediff-current-diff-Ancestor ((t (:background "#340824"))))
 '(ediff-fine-diff-A ((t (:background "#7f5200"))))
 '(ediff-fine-diff-B ((t (:background "#0f487f"))))
 '(ediff-fine-diff-Ancestor ((t (:background "#681048"))))
 '(diff-added ((t (:inherit diff-changed :foreground "steel blue"))))
 '(diff-refine-added ((t (:inherit diff-refine-changed :foreground "dodger blue"))))
 '(diff-removed ((t (:foreground "orange3" :inherit diff-changed))))
 '(diff-refine-removed ((t (:foreground "orange" :inherit diff-refine-changed))))
 '(diff-changed ((t (:background "gray25"))))
 '(diff-refine-changed ((t (:weight bold))))
 '(term-color-blue ((t (:foreground "steelblue1" :background "steelblue1"))))
 '(default ((t (:background "gray22" :foreground "white smoke" :height 100 :family "DejaVu Sans Mono")))))

(provide-theme 'eighters)
